import Head from 'next/head'
import { FaMoon } from 'react-icons/fa';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram,
  AiFillGithub,
} from "react-icons/ai";
import Image from 'next/image.js';
import deved from "../public/dev-ed-wave.png";
import weather from '../public/weather.gif';
import calculator from '../public/calculator.gif';
import code from '../public/code.gif';
import consulting from '../public/consulting.png';
import { useState } from 'react';
import arrowdown from '../public/arrowdown.gif';




export default function Home() {
  const [darkMode, setDarkmode] = useState(false);
  const iconColor = darkMode ? "white" : "gray";
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Aman Pandey Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40  dark:bg-gray-900'>
        <section className=" min-h-screen">
          <nav className='py-10 mb-12 flex justify-between '>
            <h1 className={`text-xl ${darkMode ? 'text-gray-300' : 'text-black'} font-burtons`}>@whoamanpandey</h1>
            <ul className='flex items-center'>
              <li>
                <FaMoon onClick={() => {
                  setDarkmode(!darkMode);

                }}

                  className={`cursor-pointer text-2xl dark-mode-button  transform hover:scale-110 transition duration-300 ease-in-out
              text-${iconColor}`}
                />
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'
                  href='https://drive.google.com/file/d/1vWmTymEfADNNFZEYGqukh3_C8ZWFD9wL/view?usp=sharing' target='blank'
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className='flex'>
            <div className='text-left p-10'>
              <h2 className={`text-5xl py-2 font-medium ${darkMode ? 'text-teal-400' : 'text-teal-600'} md:text-6xl mt-[50px]`}>Aman Pandey</h2>

              <h3 className={`text-2xl py-2 ${darkMode ? 'text-gray-300' : 'text-gray-800'} md:text-3xl font-serif`}>
                Developer and Learner
              </h3>
              <p className={`text-md py-3 leading-8 ${darkMode ? 'text-gray-300' : 'text-gray-800'} md:text-xl max-w-xl mx-left list-disc`}>
                "Passionate Third-Year IT Student Driven to Excel in Web Development,
                Continuously learning new technologies and striving to create innovative and user-friendly web applications".
              </p>
            </div>

            <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 mt-0 overflow-hidden md:h-80 md:w-80'>
              <Image src={deved} property='fill' />
            </div>
          </div>
          <div className='text-5xl flex justify-center items-center gap-16 pt-6 pb-6 text-gray-600'>
            <a href='https://twitter.com/whoamanpandey' target='_blank'>
              <AiFillTwitterCircle className="hover:text-blue-400 transition-colors duration-300 ease-in-out" />
            </a>
            <a href='https://www.linkedin.com/in/whoamanpandey/' target='_blank'>
              <AiFillLinkedin className="hover:text-blue-400 transition-colors duration-300 ease-in-out" />
            </a>
            <a href='https://www.instagram.com/whoamanpandey/' target='_blank'>
              <AiFillInstagram className="hover:text-blue-400 transition-colors duration-300 ease-in-out" />
            </a>
            <a href='https://github.com/amanithub' target='_blank' >
              <AiFillGithub className="hover:text-blue-400 transition-colors duration-300 ease-in-out" />
            </a>
            <div >
            <Image src={arrowdown} width={100} height={100}/>

            </div>

          </div>

        </section>
       

        <section>
          <div className='text-center h-25 mt-5'>
            <span className='text-5xl font-bold text-teal-500 '>PROJECTS</span>

          </div>
          <div className='lg:flex gap-10 mt-10'>

            <div className={`text-center shadow-lg p-10 rounded-xl my-10  ${darkMode ? 'bg-gradient-to-r from-yellow-100 to-teal-300' : 'bg-gradient-to-r from-yellow-300 to-teal-100'} hover:cursor-pointer transform hover:scale-110 transition duration-300 ease-in-out w-64`}>
              <a href="https://weatherbyamanum.netlify.app/" target='_blank' className="inline-block">
                <Image src={weather} width={100} height={100} className='mx-auto' />
              </a>
              <h3 className='text-xl font-my-10'>
                Weather Finder
              </h3>
            </div>


            <div className={`text-center shadow-lg p-10 rounded-xl my-10  ${darkMode ? 'bg-gradient-to-r from-yellow-100 to-teal-300' : 'bg-gradient-to-r from-yellow-300 to-teal-100'} hover:cursor-pointer transform hover:scale-110 transition duration-300 ease-in-out w-64`}>
              <a href="https://zomatobyamanum.netlify.app/" target='_blank'>
                <Image src={consulting} width={100} height={100} className='mx-auto' />
              </a>
              <h3 className='text-xl font-my-10'>
                Zomato Landing Page
              </h3>
           
              

            </div>

            <div className={`text-center shadow-lg p-10 rounded-xl my-10  ${darkMode ? 'bg-gradient-to-r from-yellow-100 to-teal-300' : 'bg-gradient-to-r from-yellow-300 to-teal-100'} hover:cursor-pointer transform hover:scale-110 transition duration-300 ease-in-out w-64`}>

              <a href="https://github.com/amanithub/Chat-App" target='_blank'>
                <Image src={code} width={100} height={100} className='mx-auto' />
              </a>
              <h3 className='text-xl font-my-10'>
                Chat App
              </h3>

              

            </div>


            <div className={`text-center shadow-lg p-10 rounded-xl my-10  ${darkMode ? 'bg-gradient-to-r from-yellow-100 to-teal-300' : 'bg-gradient-to-r from-yellow-300 to-teal-100'} hover:cursor-pointer transform hover:scale-110 transition duration-300 ease-in-out w-64`}>
              <a href="https://calculatorbyamanum.netlify.app/" target='_blank'>
                <Image src={calculator} width={100} height={100} className='mx-auto' />
              </a>
              <h3 className='text-xl font-my-10'>
                Calculator Web App
              </h3>

            </div>

          </div>
        </section>

      </main>
    </div>
  );
}
